import React,{useEffect,useState}from"react";
import{CheckCircle,MapPin,RefreshCw,UserPlus,UserMinus,Package,LifeBuoy}from"lucide-react";
import{supabase}from"../../../lib/supabase";
import{getLaneWorkers,getLanePickingTasks,getPickerCandidates,getPickerRequests,requestPicker,LaneWorker,LanePickingTask,PickerCandidate,PickerVendorRequest}from"../../../services/laneWorkerService";

type Item={id:string;order_id:string;product_id:string;product_name:string|null;quantity:number};
type ProductLocation={product_id:string;lane_id:string;rack_id:string|null;lane_name:string|null;rack_name:string|null};
type Order={id:string;order_number:string;order_status:string};

export default function LanePicking(){
 const[workers,setWorkers]=useState<LaneWorker[]>([]);const[candidates,setCandidates]=useState<PickerCandidate[]>([]);const[requests,setRequests]=useState<PickerVendorRequest[]>([]);
 const[orders,setOrders]=useState<Order[]>([]);const[items,setItems]=useState<Item[]>([]);const[locations,setLocations]=useState<ProductLocation[]>([]);const[tasks,setTasks]=useState<Map<string,LanePickingTask>>(new Map());
 const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[createOpen,setCreateOpen]=useState(false);const[createdPicker,setCreatedPicker]=useState<any|null>(null);const[form,setForm]=useState({full_name:"",phone:"",email:"",city:"",locality:"",address:"",pincode:"",password:""});
 const load=async()=>{setLoading(true);setError(null);try{const{data:a}=await supabase.auth.getUser();if(!a.user)throw new Error("Vendor session not found.");const{data:v,error:ve}=await supabase.from("vendors").select("id").eq("auth_user_id",a.user.id).maybeSingle();if(ve)throw ve;if(!v)throw new Error("Vendor profile not found.");const ws=await getLaneWorkers(v.id);setWorkers(ws);setCandidates(await getPickerCandidates(v.id));setRequests(await getPickerRequests(v.id));const{data:o,error:oe}=await supabase.from("orders").select("id,order_number,order_status").eq("vendor_id",v.id).order("updated_at",{ascending:false});if(oe)throw oe;setOrders((o||[]) as Order[]);const ids=(o||[]).map((x:any)=>x.id);const{data:i,error:ie}=ids.length?await supabase.from("order_items").select("id,order_id,product_id,product_name,quantity").in("order_id",ids):{data:[],error:null};if(ie)throw ie;setItems((i||[]) as Item[]);const{data:locs,error:le}=ids.length?await supabase.from("product_storage_locations").select("product_id,lane_id,rack_id,vendor_lanes(lane_name),vendor_racks(rack_name)").eq("vendor_id",v.id):{data:[],error:null};if(le)throw le;setLocations((locs||[]).map((x:any)=>({product_id:x.product_id,lane_id:x.lane_id,rack_id:x.rack_id,lane_name:x.vendor_lanes?.lane_name||null,rack_name:x.vendor_racks?.rack_name||null})));const ts=await getLanePickingTasks(v.id,(i||[]).map((x:any)=>x.id));const map=new Map<string,LanePickingTask>();ts.forEach(t=>map.set(t.order_item_id,t));setTasks(map);}catch(e:any){console.error(e);setError(e.message||"Unable to load Picker.");}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const createPicker=async()=>{setBusy("create-picker");setError(null);setMessage(null);let vendorSession:any=null;try{if(!form.full_name||!form.phone||!form.email||!form.city||!form.password)throw new Error("Fill all required Picker fields.");if(form.pincode&&!/^[0-9]{6}$/.test(form.pincode))throw new Error("Pincode must be exactly 6 digits.");if(form.password.length>4)throw new Error("Password must be maximum 4 characters.");const{data:sessionData,error:sessionError}=await supabase.auth.getSession();if(sessionError||!sessionData.session)throw new Error("Vendor session not found.");vendorSession=sessionData.session;const{data:vendor,error:vendorError}=await supabase.from("vendors").select("id").eq("auth_user_id",vendorSession.user.id).maybeSingle();if(vendorError||!vendor)throw new Error("Vendor profile not found.");const{data,error}=await supabase.auth.signUp({email:form.email.trim().toLowerCase(),password:"Rivo@"+form.password,options:{data:{picker_role:"picker",registration_source:"vendor",created_by_vendor_id:vendor.id,full_name:form.full_name.trim(),phone:form.phone.trim(),city:form.city.trim(),locality:form.locality.trim()||null,address:form.address.trim()||null,pincode:form.pincode.trim()||null}}});if(error)throw error;if(!data.user)throw new Error("Picker account was not created.");if(data.session)await supabase.auth.setSession(vendorSession);const{data:picker,error:pickerError}=await supabase.from("picker_profiles").select("id,picker_login_id,email,full_name,application_status").eq("auth_user_id",data.user.id).maybeSingle();if(pickerError)throw pickerError;if(!picker)throw new Error("Picker profile was not created. Run the Picker auth trigger SQL in Supabase first.");const{data:approved,error:approveError}=await supabase.from("picker_profiles").update({application_status:"approved",updated_at:new Date().toISOString()}).eq("id",picker.id).eq("created_by_vendor_id",vendor.id).select("id,picker_login_id,email,full_name,application_status").single();if(approveError)throw approveError;const{error:workerError}=await supabase.from("vendor_workers").insert({vendor_id:vendor.id,auth_user_id:data.user.id,worker_name:form.full_name.trim(),status:"active"});if(workerError)throw workerError;setCreatedPicker(approved);setCreateOpen(false);setMessage("Picker created, approved and linked to this vendor.");setForm({full_name:"",phone:"",email:"",city:"",locality:"",address:"",pincode:"",password:""});await load()}catch(e:any){if(vendorSession){await supabase.auth.setSession(vendorSession).catch(()=>{})}setError(e.message||"Unable to create Picker.")}finally{setBusy(null)}};
 const request=async(pickerId:string)=>{setBusy(pickerId);try{const{data:a}=await supabase.auth.getUser();if(!a.user)throw new Error("Vendor session not found.");const{data:v}=await supabase.from("vendors").select("id").eq("auth_user_id",a.user.id).maybeSingle();if(!v)throw new Error("Vendor profile not found.");await requestPicker(v.id,pickerId);await load()}catch(e:any){setError(e.message||"Unable to request Picker.")}finally{setBusy(null)}};
 const remove=async(workerId:string)=>{if(!confirm("Remove this Picker from your store?"))return;setBusy(workerId);try{const{data:a}=await supabase.auth.getUser();if(!a.user)throw new Error("Vendor session not found.");const{data:v}=await supabase.from("vendors").select("id").eq("auth_user_id",a.user.id).maybeSingle();if(!v)throw new Error("Vendor profile not found.");await removeLaneWorker(workerId,v.id);await load()}catch(e:any){setError(e.message||"Unable to remove Picker.")}finally{setBusy(null)}};
 const pendingRequests=new Set(requests.filter(r=>r.status==="pending").map(r=>r.picker_id));
 const requestHelper=async()=>{setBusy("helper");setError(null);try{const{data:a}=await supabase.auth.getUser();if(!a.user)throw new Error("Vendor session not found.");const{data:v}=await supabase.from("vendors").select("id").eq("auth_user_id",a.user.id).maybeSingle();if(!v)throw new Error("Vendor profile not found.");const{error}=await supabase.from("vendor_support_tickets").insert({vendor_id:v.id,issue_type:"picker_helper",title:"Request Picker Helper",description:"Vendor requested a Picker/helper for store picking operations.",priority:"medium",status:"open",screenshot_url:null});if(error)throw error;setMessage("Helper request sent to Rivo Admin Support.");}catch(e:any){setError(e.message||"Unable to request helper.")}finally{setBusy(null)}};
 const pickable=items.filter(i=>{const s=orders.find(o=>o.id===i.order_id)?.order_status?.toLowerCase();return !["cancelled","delivered","picked_up","out_for_delivery"].includes(s||"")});
 return <div className="p-4 lg:p-6 space-y-6 bg-background text-foreground min-h-screen">
  <div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-bold">RivoCity Picker</h1><p className="text-sm text-muted-foreground mt-1">Recruit a nearby Picker, create store Pickers and assign order items.</p></div><div className="flex gap-2"><button onClick={()=>setCreateOpen(true)} className="h-9 px-3 rounded-lg bg-emerald-600 text-white text-sm font-bold flex items-center gap-2"><UserPlus className="w-4 h-4"/>Create Picker</button><button onClick={load} className="h-9 px-3 rounded-lg border border-border bg-card text-sm font-semibold flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh</button></div></div>
  {createdPicker&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-800 px-4 py-3 text-sm"><b>Picker created:</b> {createdPicker.picker_login_id} · {createdPicker.email}. Give the Picker this ID and their 4-character password.</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 text-red-700 px-4 py-3 text-sm">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-700 px-4 py-3 text-sm">{message}</div>}
  {loading?<div className="py-16 flex justify-center"><RefreshCw className="animate-spin"/></div>:<>
   <section className="bg-card border border-border rounded-xl p-4">
    <div className="flex items-center justify-between"><div><h2 className="font-bold">My Picker</h2><p className="text-xs text-muted-foreground mt-1">Approved Pickers near your store.</p></div><span className="text-xs font-bold text-emerald-600">{workers.length} active</span></div>
    {workers.length===0?<p className="text-sm text-muted-foreground mt-4">No Picker assigned yet. Request one below.</p>:<div className="space-y-2 mt-4">{workers.map(w=><div key={w.id} className="flex items-center justify-between border border-border rounded-lg p-3"><div><p className="font-semibold">{w.worker_name}</p><p className="text-xs text-muted-foreground">Active Picker</p></div><button onClick={()=>remove(w.id)} disabled={busy===w.id} className="text-xs font-bold text-red-600 flex items-center gap-1"><UserMinus className="w-4 h-4"/>Remove</button></div>)}</div>}
   </section>
   <section className="bg-card border border-border rounded-xl p-4">
    <div><h2 className="font-bold">Nearby available Pickers</h2><p className="text-xs text-muted-foreground mt-1">Location is used to sort available approved Pickers closest to your store.</p></div>
    {candidates.length===0?<p className="text-sm text-muted-foreground mt-4">No approved available Pickers found.</p>:<div className="space-y-2 mt-4">{candidates.map(p=><div key={p.id} className="flex items-center justify-between border border-border rounded-lg p-3 gap-3"><div className="min-w-0"><p className="font-semibold truncate">{p.full_name}</p><p className="text-xs text-muted-foreground flex items-center gap-1"><MapPin className="w-3 h-3"/>{p.distanceKm===null?"Distance unavailable":p.distanceKm.toFixed(1)+" km"}{p.locality?" · "+p.locality:""}</p></div>{pendingRequests.has(p.id)?<span className="text-xs font-bold text-amber-600">Requested</span>:<button onClick={()=>request(p.id)} disabled={busy===p.id} className="shrink-0 rounded-lg bg-emerald-600 text-white px-3 py-2 text-xs font-bold flex items-center gap-1"><UserPlus className="w-4 h-4"/>{busy===p.id?"Sending":"Request"}</button>}</div>)}</div>}
   {requests.filter(r=>r.status!=="pending").length>0&&<div className="mt-4 border-t border-border pt-3"><p className="text-xs font-bold text-muted-foreground uppercase">Recent requests</p>{requests.slice(0,5).map(r=><div key={r.id} className="text-xs flex justify-between mt-2"><span>{r.status}</span><span className="text-muted-foreground">{new Date(r.requested_at).toLocaleString()}</span></div>)}</div>}
   </section>
   <section className="space-y-3">
    <div><h2 className="font-bold">Assign order items</h2><p className="text-xs text-muted-foreground mt-1">Only orders that have not reached pickup/delivery are shown.</p></div>
    {pickable.length===0?<div className="bg-card border border-border rounded-xl p-6 text-sm text-muted-foreground">No pickable order items right now.</div>:pickable.map(item=>{const order=orders.find(o=>o.id===item.order_id);const task=tasks.get(item.id);return <div key={item.id} className="bg-card border border-border rounded-xl p-4"><div className="flex items-start gap-3"><Package className="w-5 h-5 text-emerald-600 mt-0.5"/><div className="flex-1"><p className="text-xs font-bold text-muted-foreground">Order {order?.order_number||"—"}</p><p className="font-semibold mt-1">{item.product_name||"Product"}</p><p className="text-xs text-muted-foreground">Quantity {item.quantity}</p>{locations.filter(l=>l.product_id===item.product_id).map(l=><p key={l.lane_id+"-"+(l.rack_id||"none")} className="text-xs font-semibold text-emerald-700 mt-1">Location: {l.lane_name||"Lane"}{l.rack_name?" → "+l.rack_name:""}</p>)}</div>{task?.status==="picked"&&<CheckCircle className="w-5 h-5 text-emerald-600"/>}</div><div className="mt-3 rounded-lg border bg-muted/30 px-3 py-2"><p className="text-xs font-bold text-emerald-700">{task?.worker_id ? "Automatically assigned to lane Picker" : "Waiting for lane Picker"}</p>{task?.basket_code&&<p className="text-xs text-muted-foreground mt-1">Basket: <span className="font-bold text-foreground">{task.basket_code}</span> · Picker places the item in this basket.</p>}{!task?.worker_id&&<p className="text-xs text-muted-foreground mt-1">Assign a Picker to the product's lane in Lanes & Racks.</p>}</div></div>})}
   </section>
  </>}
 {createOpen&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-card border shadow-xl p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Create Picker</h2><button onClick={()=>setCreateOpen(false)} className="text-muted-foreground">×</button></div><p className="text-xs text-muted-foreground mt-1">Vendor-created Pickers are approved immediately and visible to Admin.</p><div className="grid grid-cols-2 gap-3 mt-4">{[["full_name","Full name"],["phone","Phone"],["email","Email"],["city","City"],["locality","Area / locality"],["address","Address"],["pincode","Pincode (6 digits)"],["password","Password (max 4)"]].map(([key,label])=><label key={key} className="text-xs font-bold text-muted-foreground"><span>{label}</span><input type={key==="password"?"password":key==="email"?"email":"text"} maxLength={key==="pincode"?6:key==="password"?4:undefined} value={(form as any)[key]} onChange={e=>setForm(v=>({...v,[key]:key==="password"?e.target.value.slice(0,4):key==="pincode"?e.target.value.replace(/\D/g,"").slice(0,6):e.target.value}))} className="mt-1 w-full h-10 rounded-lg border px-3 bg-background"/></label>)}</div><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setCreateOpen(false)} className="px-4 py-2 rounded-lg border text-sm font-bold">Cancel</button><button disabled={busy==="create-picker"} onClick={createPicker} className="px-4 py-2 rounded-lg bg-emerald-600 text-white text-sm font-bold">{busy==="create-picker"?"Creating…":"Create Picker"}</button></div></div></div>}
 </div>
}